# Generated by Django 5.0.1 on 2024-01-10 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_user_options_alter_image_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pereval',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.level'),
        ),
    ]
